/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazGrafica;

import Metodos.Coincidencia;
import Metodos.Utilidades;
import java.util.List;

/**
 *
 * @author Jhonathan Alexander Ludeña Cevallos
 */
public class Principal extends javax.swing.JFrame {
    
    int clic =0;
    
     Utilidades u = new Utilidades();
    
    List<Integer> siguiente = u.filasTablaCompleta();
    
    public Principal() {
        initComponents();
        this.setTitle("Juego de Memoria");
        this.setLocationRelativeTo(this);
        u.imgInicio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        cartaUno = new javax.swing.JButton();
        cartaDos = new javax.swing.JButton();
        cartaTres = new javax.swing.JButton();
        cartaCuatro = new javax.swing.JButton();
        cartaCinco = new javax.swing.JButton();
        cartaSeis = new javax.swing.JButton();
        cartaSiete = new javax.swing.JButton();
        cartaOcho = new javax.swing.JButton();

        jButton3.setText("jButton1");

        jButton4.setText("jButton1");

        jButton5.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cartaUno.setForeground(new java.awt.Color(240, 240, 240));
        cartaUno.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cartaUno.setMaximumSize(new java.awt.Dimension(64, 64));
        cartaUno.setMinimumSize(new java.awt.Dimension(64, 64));
        cartaUno.setPreferredSize(new java.awt.Dimension(64, 64));
        cartaUno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cartaUnoMouseClicked(evt);
            }
        });

        cartaDos.setForeground(new java.awt.Color(240, 240, 240));
        cartaDos.setMaximumSize(new java.awt.Dimension(64, 64));
        cartaDos.setMinimumSize(new java.awt.Dimension(64, 64));
        cartaDos.setPreferredSize(new java.awt.Dimension(64, 64));
        cartaDos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cartaDosMouseClicked(evt);
            }
        });

        cartaTres.setForeground(new java.awt.Color(240, 240, 240));
        cartaTres.setMaximumSize(new java.awt.Dimension(64, 64));
        cartaTres.setMinimumSize(new java.awt.Dimension(64, 64));
        cartaTres.setPreferredSize(new java.awt.Dimension(64, 64));
        cartaTres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cartaTresMouseClicked(evt);
            }
        });

        cartaCuatro.setForeground(new java.awt.Color(240, 240, 240));
        cartaCuatro.setMaximumSize(new java.awt.Dimension(64, 64));
        cartaCuatro.setMinimumSize(new java.awt.Dimension(64, 64));
        cartaCuatro.setPreferredSize(new java.awt.Dimension(64, 64));
        cartaCuatro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cartaCuatroMouseClicked(evt);
            }
        });

        cartaCinco.setForeground(new java.awt.Color(240, 240, 240));
        cartaCinco.setMaximumSize(new java.awt.Dimension(64, 64));
        cartaCinco.setMinimumSize(new java.awt.Dimension(64, 64));
        cartaCinco.setPreferredSize(new java.awt.Dimension(64, 64));
        cartaCinco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cartaCincoMouseClicked(evt);
            }
        });

        cartaSeis.setForeground(new java.awt.Color(240, 240, 240));
        cartaSeis.setMaximumSize(new java.awt.Dimension(64, 64));
        cartaSeis.setMinimumSize(new java.awt.Dimension(64, 64));
        cartaSeis.setPreferredSize(new java.awt.Dimension(64, 64));
        cartaSeis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cartaSeisMouseClicked(evt);
            }
        });

        cartaSiete.setForeground(new java.awt.Color(240, 240, 240));
        cartaSiete.setMaximumSize(new java.awt.Dimension(64, 64));
        cartaSiete.setMinimumSize(new java.awt.Dimension(64, 64));
        cartaSiete.setPreferredSize(new java.awt.Dimension(64, 64));
        cartaSiete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cartaSieteMouseClicked(evt);
            }
        });

        cartaOcho.setForeground(new java.awt.Color(240, 240, 240));
        cartaOcho.setMaximumSize(new java.awt.Dimension(64, 64));
        cartaOcho.setMinimumSize(new java.awt.Dimension(64, 64));
        cartaOcho.setPreferredSize(new java.awt.Dimension(64, 64));
        cartaOcho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cartaOchoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cartaDos, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cartaUno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cartaTres, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cartaCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cartaCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cartaSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cartaSiete, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cartaOcho, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cartaSiete, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cartaOcho, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cartaCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cartaSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cartaTres, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cartaCuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cartaUno, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cartaDos, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cartaUnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartaUnoMouseClicked
        // TODO add your handling code here:
        Coincidencia c = new Coincidencia();
        c.setBoton(cartaUno);
        c.setNumeroBtnon(1);
        c.setValorCoincidencia(siguiente.get(0));
        u.getCoincidencia().add(c);
        u.pintarCoincidencia();
        u.coincidencia();
    }//GEN-LAST:event_cartaUnoMouseClicked

    private void cartaDosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartaDosMouseClicked
        // TODO add your handling code here:
        Coincidencia c = new Coincidencia();
        c.setBoton(cartaDos);
        c.setNumeroBtnon(2);
        c.setValorCoincidencia(siguiente.get(1));
        u.getCoincidencia().add(c);
        u.pintarCoincidencia();
        u.coincidencia();
    }//GEN-LAST:event_cartaDosMouseClicked

    private void cartaTresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartaTresMouseClicked
        // TODO add your handling code here:
        Coincidencia c = new Coincidencia();
        c.setBoton(cartaTres);
        c.setNumeroBtnon(3);
        c.setValorCoincidencia(siguiente.get(2));
        u.getCoincidencia().add(c);
        u.pintarCoincidencia();
        u.coincidencia();
    }//GEN-LAST:event_cartaTresMouseClicked

    private void cartaCuatroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartaCuatroMouseClicked
        Coincidencia c = new Coincidencia();
        c.setBoton(cartaCuatro);
        c.setNumeroBtnon(4);
        c.setValorCoincidencia(siguiente.get(3));
        u.getCoincidencia().add(c);
        u.pintarCoincidencia();
        u.coincidencia();
    }//GEN-LAST:event_cartaCuatroMouseClicked

    private void cartaCincoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartaCincoMouseClicked
        Coincidencia c = new Coincidencia();
        c.setBoton(cartaCinco);
        c.setNumeroBtnon(5);
        c.setValorCoincidencia(siguiente.get(4));
        u.getCoincidencia().add(c);
        u.pintarCoincidencia();
        u.coincidencia();
    }//GEN-LAST:event_cartaCincoMouseClicked

    private void cartaSeisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartaSeisMouseClicked
        Coincidencia c = new Coincidencia();
        c.setBoton(cartaSeis);
        c.setNumeroBtnon(6);
        c.setValorCoincidencia(siguiente.get(5));
        u.getCoincidencia().add(c);
        u.pintarCoincidencia();
        u.coincidencia();
    }//GEN-LAST:event_cartaSeisMouseClicked

    private void cartaSieteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartaSieteMouseClicked
        Coincidencia c = new Coincidencia();
        c.setBoton(cartaSiete);
        c.setNumeroBtnon(7);
        c.setValorCoincidencia(siguiente.get(6));
        u.getCoincidencia().add(c);
        u.pintarCoincidencia();
        u.coincidencia();
    }//GEN-LAST:event_cartaSieteMouseClicked

    private void cartaOchoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartaOchoMouseClicked
        Coincidencia c = new Coincidencia();
        c.setBoton(cartaOcho);
        c.setNumeroBtnon(8);
        c.setValorCoincidencia(siguiente.get(7));
        u.getCoincidencia().add(c);
        u.pintarCoincidencia();
        u.coincidencia();
    }//GEN-LAST:event_cartaOchoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton cartaCinco;
    public static javax.swing.JButton cartaCuatro;
    public static javax.swing.JButton cartaDos;
    public static javax.swing.JButton cartaOcho;
    public static javax.swing.JButton cartaSeis;
    public static javax.swing.JButton cartaSiete;
    public static javax.swing.JButton cartaTres;
    public static javax.swing.JButton cartaUno;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    // End of variables declaration//GEN-END:variables
}
